version: "3"
services:
  iac-dev-container:
    build:
      context: ../
      dockerfile: Dockerfile
    container_name: IaCDevContainer
    image: iac-dev-container:latest
    volumes:
      - "iac-dev-container-data:/var/iac-dev-container-data"
      - "../..:/workspace"
volumes:
  iac-dev-container-data:
    external: false

